# Generated by Django 4.2.7 on 2025-06-29 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.IntegerField(choices=[(1, '신규'), (2, '진행중'), (3, '해결됨'), (4, '피드백'), (5, '종료'), (6, '거부됨')], default=1)),
                ('assigned_to_id', models.IntegerField(blank=True, null=True)),
                ('priority_id', models.IntegerField(choices=[(1, '낮음'), (2, '보통'), (3, '높음'), (4, '긴급'), (5, '즉시')], default=2)),
                ('author_id', models.IntegerField()),
                ('lock_version', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('done_ratio', models.IntegerField(default=0)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('root_id', models.IntegerField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=1)),
                ('default_done_ratio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue_statuses',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_in_chlog', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=1)),
                ('is_in_roadmap', models.BooleanField(default=True)),
                ('fields_bits', models.IntegerField(default=0)),
                ('default_status_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trackers',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('activity_id', models.IntegerField()),
                ('spent_on', models.DateField()),
                ('tyear', models.IntegerField()),
                ('tmonth', models.IntegerField()),
                ('tweek', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='redmine.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmine.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_entries',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redmine.project'),
        ),
    ]
