# Generated by Django 4.2.7 on 2025-06-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('redmine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedmineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=255)),
                ('admin', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=1)),
                ('last_login_on', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('auth_source_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_notification', models.CharField(default='', max_length=255)),
                ('salt', models.CharField(blank=True, max_length=64, null=True)),
                ('must_change_passwd', models.BooleanField(default=False)),
                ('passwd_changed_on', models.DateTimeField(blank=True, null=True)),
                ('twofa_scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('twofa_totp_key', models.CharField(blank=True, max_length=255, null=True)),
                ('twofa_totp_last_used_at', models.IntegerField(blank=True, null=True)),
                ('twofa_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='is_in_chlog',
        ),
        migrations.AddField(
            model_name='project',
            name='default_assigned_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_version_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='homepage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='inherit_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rgt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='redmine.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='issue',
            field=models.ForeignKey(blank=True, db_column='issue_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='redmine.issue'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='redmine.project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
