# Generated by Django 4.2.7 on 2025-06-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redmine', '0002_redmineuser_remove_tracker_is_in_chlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='redmine.redmineuser'),
        ),
    ]
